driver:
  name: terraform
  root_module_directory: test/fixtures

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:    
    - name: local
      backend: local

platforms:
  - name: aws-basic-network-private-subents
    driver:
      variable_files:
        - test/fixtures/test.with-private.tfvars

  - name: aws-basic-network-no-private-subents
    driver:
      variable_files:
        - test/fixtures/test.no-private.tfvars

suites:
  - name: default
